apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-clone-pvc
spec:
  storageClassName: vmstore-csi-file-driver-sc
  dataSource:
    name: snapshot-nginx-demo-pvc
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
