apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cloned-pvc
  namespace: website
spec:
  storageClassName: vmstore-csi-file-driver-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: vmstore-snapshot-nginx-pvc
    namespace: default
