apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: vmstore-csi-file-driver-sc
