---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOY_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DEPLOY_NAME}
  template:
    metadata:
      labels:
        app: ${DEPLOY_NAME}
    spec:
      containers:
      - name: fio
        image: ljishen/fio
        command:
        - /bin/sh
        - -c
        - |
          set -e
          fallocate -l 10G /data/testfile || dd if=/dev/zero of=/data/testfile bs=1M count=10240
          fio --name=${PROFILE}demo-pvc-perf \\
          --filename=/data/testfile \\
          --bs=8k \\
          --size=10G \\
          --rw=randrw \\
          --rwmixread=${RWMIX} \\
          --iodepth=4 \\
          --numjobs=1 \\
          --direct=1 \\
          --runtime=600 \\
          --time_based \\
          --group_reporting \\
          --ioengine=libaio \\
          --thread
        volumeMounts:
        - name: fio-pvc
          mountPath: /data
      volumes:
      - name: fio-pvc
        persistentVolumeClaim:
          claimName: ${PVC_NAME}
