---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ${STORAGE_CLASS_NAME:-tintri-csi-rw-sc}
provisioner: vmstore.csi.tintri.com
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  fileSystemType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME:-tintri-csi-workload-pvc}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_SIZE:-20Gi}
  storageClassName: ${STORAGE_CLASS_NAME:-tintri-csi-rw-sc}
